# vim: ft=ansible:
---
- hosts: all
  remote_user: vagrant
  become: yes
  become_user: root

  vars:
    - deploy_container_name: deploy.web.web.v0-i1-d0

  tasks:

  - name: Ensure FORWARD chain policy is ACCEPT
    command: iptables -P FORWARD ACCEPT

  - name: Ensure INPUT chain policy is ACCEPT
    command: iptables -P INPUT ACCEPT

  - name: Ensure dnsmasq in resolv.conf
    lineinfile: dest=/etc/resolv.conf line='nameserver 127.0.0.1' insertbefore=BOF

  - name: Ensure health statuses of vital services
    service: name={{ item }} state=restarted
    with_items:
      - lainlet
      - networkd
      - etcd

  - name: Bring deploy back to life
    command: docker start {{ deploy_container_name }}

  - debug: msg="Recovery operation finished, deploy will bring containers back one by one, check `docker ps -a` for progress."
...
